spring:
  application:
    name: contact_prod
  config:
    activate:
      on-profile: prod
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: # aws 사용시 parameter store 사용시 properties 에서 암/복호화 가능
  jpa:
    hibernate:
      ddl-auto: create-drop #시작 할때 스키마를 생성하고 세션을 종료할때 삭제
    show-sql: true

server:
  port: 8080

---
spring:
  application:
    name: contact_dev
  config:
    activate:
      on-profile: dev
server:
  port: 8081